apiVersion: apps/v1
kind: Deployment
metadata:
  name: adservice
  namespace: online-shop-microservices
  labels:
    app: adservice
spec:
  selector:
    matchLabels:
      app: adservice
  template:
    metadata:
      labels:
        app: adservice
    spec:
      containers:
      - name: adservice
        image: docker.io/hopa/adservice
        ports:
        - containerPort: 9555
        env:
          - name: PORT
            value: "9555"
   
