apiVersion: v1
kind: Service
metadata:
  name: cartservice
  namespace: online-shop-microservices
spec:
  type: ClusterIP
  selector:
    app: cartservice
  ports:
    - protocol: TCP
      port: 7070
      targetPort: 7070