apiVersion: apps/v1
kind: Deployment
metadata:
  name: checkoutservice
  namespace: online-shop-microservices
  labels:
    app: checkoutservice
spec:
  selector:
    matchLabels:
      app: checkoutservice
  template:
    metadata:
      labels:
        app: checkoutservice
    spec:
      containers:
      - name: checkoutservice
        image: gcr.io/google-samples/microservices-demo/checkoutservice:v0.1.0
        ports:
        - containerPort: 5050
        env:
          - name: PORT
            value: "5050"
          - name: SHIPPING_SERVICE_ADDR
            value: "shippingservice:50051"
          - name: PRODUCT_CATALOG_SERVICE_ADDR
            value: "productcatalogservice:3550"
          - name: CART_SERVICE_ADDR
            value: "cartservice:7070"
          - name: EMAIL_SERVICE_ADDR
            value: "emailservice:8080"
          - name: PAYMENT_SERVICE_ADDR
            value: "paymentservice:50051"
          - name: CURRENCY_SERVICE_ADDR
            value: "currencyservice:7000"

