apiVersion: apps/v1
kind: Deployment
metadata:
  name: emailservice
  namespace: online-shop-microservices
  labels:
    app: EmailService
spec:
  selector:
    matchLabels:
      app: EmailService
  template:
    metadata:
      labels:
        app: EmailService
    spec:
      containers:
      - name: emailservice
        image: gcr.io/google-samples/microservices-demo/emailservice:v0.1.0
        ports:
        - containerPort: 8080
        env:
          - name: PORT
            value: "8080" 
