apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: online-shop-microservices
spec:
  type: NodePort
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 30000