apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: online-shop-microservices
  labels:
    app: frontend
spec:
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: gcr.io/google-samples/microservices-demo/frontend:v0.1.0
        ports:
        - containerPort: 8080
        env:
          - name: PORT
            value: "8080"
          - name: SHIPPING_SERVICE_ADDR
            value: "shippingservice:50051"
          - name: PRODUCT_CATALOG_SERVICE_ADDR
            value: "productcatalogservice:3550"
          - name: CART_SERVICE_ADDR
            value: "cartservice:7070"
          - name: RECOMMENDATION_SERVICE_ADDR
            value: "recommedationservice:8080"
          - name: CHECKOUT_SERVICE_ADDR
            value: "checkoutservice:5050"
          - name: CURRENCY_SERVICE_ADDR
            value: "currencyservice:7000"
          - name: "AD_SERVICE_ADDR"
            value: "adservice:9555"