apiVersion: v1
kind: Service
metadata:
  name: productcatalogservice
  namespace: online-shop-microservices
spec:
  type: ClusterIP
  selector:
    app: productcatalogservice
  ports:
    - protocol: TCP
      port: 3550
      targetPort: 3550