apiVersion: v1
kind: Service
metadata:
  name: recommedationservice
  namespace: online-shop-microservices
spec:
  type: ClusterIP
  selector:
    app: recommedationservice
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080

