apiVersion: v1
kind: Service
metadata:
  name: shippingservice
  namespace: online-shop-microservices
spec:
  type: ClusterIP
  selector:
    app: shippingservice
  ports:
    - protocol: TCP
      port: 50051
      targetPort: 50051

