apiVersion: apps/v1
kind: Deployment
metadata:
  name: shippingservice
  namespace: online-shop-microservices
  labels:
    app: shippingservice
spec:
  selector:
    matchLabels:
      app: shippingservice
  template:
    metadata:
      labels:
        app: shippingservice
    spec:
      containers:
      - name: shippingservice
        image: gcr.io/google-samples/microservices-demo/shippingservice:v0.1.0
        ports:
        - containerPort: 50051
        env:
          - name: PORT
            value: "50051"
