apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{.Values.appName }}
  namespace: online-shop-microservices
  labels:
    app: {{.Values.appName }}
spec:
  replicas: 2
  selector:
    matchLabels:
      app: {{.Values.appName }}
  template:
    metadata:
      labels:
        app: {{.Values.appName }}
    spec:
      containers:
      - name: {{.Values.appName }}
        image: "{{.Values.appImage }}:{{.Values.appVersion }}"
        ports:
        - containerPort: {{.Values.containerPort}}
        volumeMounts:
          - name: {{.Values.volumeName}}
            mountPath: {{.Values.volumeContainerMountPath }}
        # livenessProbe:
        #   initialDelaySeconds: 5
        #   periodSeconds: 5
        #   tcpSocket:
        #      port: 6379
        # readinessProbe:
        #   initialDelaySeconds: 5
        #   periodSeconds: 5
        #   tcpSocket:
        #      port: 6379
        # resources:
        #   requests:
        #     cpu: 70m
        #     memory: 150Mi
        #   limits:
        #     cpu: 120m
        #     memory: 300Mi
      volumes:
        - name: {{.Values.volumeName}}
          emptyDir: {}
      
            
