appName: checkoutservice
appImage: gcr.io/google-samples/microservices-demo/checkoutservice
appversion: v0.2.3
appReplicas: 2
containerPort: 5050
containerEnvVars:
    - name: PORT
      value: "5050"
envFrom:
    - configMapRef:
        name: my-envs-app
servicePort: 5050