appName: emailservice
appImage: gcr.io/google-samples/microservices-demo/emailservice
appversion: v0.2.3
appReplicas: 2
containerPort: 8080
containerEnvVars:
     - name: PORT
       value: "8080" 
     - name: DISABLE_TRACKING
       value: "1"
     - name: DISABLE_PROFILER
       value: "1"
       
servicePort: 8080