appName: frontend
appImage: gcr.io/google-samples/microservices-demo/frontend
appversion: v0.2.3
appReplicas: 2
containerPort: 8080
containerEnvVars:
   - name: PORT
     value: "8080"
envFrom:
  - configMapRef:
    name: my-envs-app
    
servicePort: 80
serviceType: NodePort
nodePort: 30000
