appName: recommedationservice
appImage: gcr.io/google-samples/microservices-demo/recommedationservice
appversion: v0.2.3
appReplicas: 2
containerPort: 3550
containerEnvVars:
- name: PORT
  value: "8080" 
- name: DISABLE_TRACKING
  value: "1"
- name: DISABLE_PROFILER
  value: "1"
- name: PRODUCT_CATALOG_SERVICE_ADDR
  valueFrom:
    configMapKeyRef:
      name: my-envs-app
      key: PRODUCT_CATALOG_SERVICE_ADDR
    
servicePort: 3550