apiVersion: v1
kind: Service
metadata:
  name: adservice
  namespace: online-shop-microservices
spec:
  type: ClusterIP
  selector:
    app: adservice
  ports:
    - protocol: TCP
      port: 9555
      targetPort: 9555