apiVersion: v1
kind: Service
metadata:
  name: checkoutservice
  namespace: online-shop-microservices
spec:
  type: ClusterIP
  selector:
    app: checkoutservice
  ports:
    - protocol: TCP
      port: 5050
      targetPort: 5050