apiVersion: v1
kind: Service
metadata:
  name: currencyservice
  namespace: online-shop-microservices
spec:
  type: ClusterIP
  selector:
    app: currencyservice
  ports:
    - protocol: TCP
      port: 7000
      targetPort: 7000