apiVersion: v1
kind: Service
metadata:
  name: emailservice
  namespace: online-shop-microservices
spec:
  type: ClusterIP
  selector:
    app: emailservice
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 8080