apiVersion: apps/v1
kind: Deployment
metadata:
  name: adservice
  namespace: online-shop-microservices
  labels:
    app: adservice
spec:
  replicas: 2
  selector:
    matchLabels:
      app: adservice
  template:
    metadata:
      labels:
        app: adservice
    spec:
      containers:
      - name: adservice
        #image: docker.io/hopa/adservice
        image: gcr.io/google-samples/microservices-demo/adservice:v0.2.3
        ports:
        - containerPort: 9555
        env:
          - name: PORT
            value: "9555"
        livenessProbe:
          periodSeconds: 5
          exec:
             command: ["/bin/grpc_health_probe","-addr=:9555"]
        readinessProbe:
          periodSeconds: 5
          exec:
             command: ["/bin/grpc_health_probe","-addr=:9555"]
        resources:
          requests:
            cpu: 150m
            memory: 100Mi
          limits:
            cpu: 250m
            memory: 200Mi