apiVersion: apps/v1
kind: Deployment
metadata:
  name: cartservice
  namespace: online-shop-microservices
  labels:
    app: cartservice
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cartservice
  template:
    metadata:
      labels:
        app: cartservice
    spec:
      containers:
      - name: cartservice
        image: gcr.io/google-samples/microservices-demo/cartservice:v0.2.3
        ports:
        - containerPort: 7070
        env:
          - name: PORT
            value: "7070"
        envFrom:
          - configMapRef:
              name: my-envs-app
        livenessProbe:
          periodSeconds: 5
          exec:
             command: ["/bin/grpc_health_probe","-addr=:7070"]
        readinessProbe:
          periodSeconds: 5
          exec:
             command: ["/bin/grpc_health_probe","-addr=:7070"]
        resources:
          requests:
            cpu: 100m
            memory: 64Mi
          limits:
            cpu: 200m
            memory: 128Mi
