apiVersion: apps/v1
kind: Deployment
metadata:
  name: checkoutservice
  namespace: online-shop-microservices
  labels:
    app: checkoutservice
spec:
  selector:
    matchLabels:
      app: checkoutservice
  template:
    metadata:
      labels:
        app: checkoutservice
    spec:
      containers:
      - name: checkoutservice
        image: gcr.io/google-samples/microservices-demo/checkoutservice:v0.1.0
        ports:
        - containerPort: 5050
        env:
          - name: PORT
            value: "5050"
        envFrom:
          - configMapRef:
              name: my-envs-app

