apiVersion: apps/v1
kind: Deployment
metadata:
  name: checkoutservice
  namespace: online-shop-microservices
  labels:
    app: checkoutservice
spec:
  replicas: 2
  selector:
    matchLabels:
      app: checkoutservice
  template:
    metadata:
      labels:
        app: checkoutservice
    spec:
      containers:
      - name: checkoutservice
        image: gcr.io/google-samples/microservices-demo/checkoutservice:v0.2.3
        ports:
        - containerPort: 5050
        env:
          - name: PORT
            value: "5050"
        envFrom:
          - configMapRef:
              name: my-envs-app
        livenessProbe:
          periodSeconds: 5
          exec:
             command: ["/bin/grpc_health_probe","-addr=:5050"]
        readinessProbe:
          periodSeconds: 5
          exec:
             command: ["/bin/grpc_health_probe","-addr=:5050"]
        resources:
          requests:
            cpu: 100m
            memory: 64Mi
          limits:
            cpu: 200m
            memory: 128Mi
