apiVersion: apps/v1
kind: Deployment
metadata:
  name: currencyservice
  namespace: online-shop-microservices
  labels:
    app: currencyservice
spec:
  selector:
    matchLabels:
      app: currencyservice
  template:
    metadata:
      labels:
        app: currencyservice
    spec:
      containers:
      - name: currencyservice
        image: gcr.io/google-samples/microservices-demo/currencyservice:v0.1.0
        ports:
        - containerPort: 7000
        env:
          - name: PORT
            value: "7000"
