apiVersion: apps/v1
kind: Deployment
metadata:
  name: emailservice
  namespace: online-shop-microservices
  labels:
    app: EmailService
spec:
  selector:
    matchLabels:
      app: EmailService
  template:
    metadata:
      labels:
        app: EmailService
    spec:
      containers:
      - name: emailservice
        image: gcr.io/google-samples/microservices-demo/emailservice:v0.2.3
        ports:
        - containerPort: 8080
        env:
          - name: PORT
            value: "8080" 
          - name: DISABLE_TRACKING
            value: "1"
          - name: DISABLE_PROFILER
            value: "1"
        livenessProbe:
          periodSeconds: 5
          exec:
             command: ["/bin/grpc_health_probe","-addr=:8080"]
        readinessProbe:
          periodSeconds: 5
          exec:
             command: ["/bin/grpc_health_probe","-addr=:8080"]
