apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: online-shop-microservices
  labels:
    app: frontend
spec:
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: gcr.io/google-samples/microservices-demo/frontend:v0.2.3
        ports:
        - containerPort: 8080
        env:
          - name: PORT
            value: "8080"
        envFrom:
          - configMapRef:
              name: my-envs-app
        livenessProbe:
          periodSeconds: 5
          exec:
             command: ["/bin/grpc_health_probe","-addr=:8080"]
        readinessProbe:
          periodSeconds: 5
          exec:
             command: ["/bin/grpc_health_probe","-addr=:8080"]
        resources:
          requests:
            cpu: 100m
            memory: 64Mi
          limits:
            cpu: 200m
            memory: 128Mi