apiVersion: apps/v1
kind: Deployment
metadata:
  name: paymentservice
  namespace: online-shop-microservices
  labels:
    app: paymentservice
spec:
  selector:
    matchLabels:
      app: paymentservice
  template:
    metadata:
      labels:
        app: paymentservice
    spec:
      containers:
      - name: paymentservice
        image: gcr.io/google-samples/microservices-demo/paymentservice:v0.2.3
        ports:
        - containerPort: 50051
        env:
          - name: PORT
            value: "50051"
        livenessProbe:
          periodSeconds: 5
          exec:
             command: ["/bin/grpc_health_probe","-addr=:50051"]
        readinessProbe:
          periodSeconds: 5
          exec:
             command: ["/bin/grpc_health_probe","-addr=:50051"]
