apiVersion: apps/v1
kind: Deployment
metadata:
  name: paymentservice
  namespace: online-shop-microservices
  labels:
    app: paymentservice
spec:
  selector:
    matchLabels:
      app: paymentservice
  template:
    metadata:
      labels:
        app: paymentservice
    spec:
      containers:
      - name: paymentservice
        image: gcr.io/google-samples/microservices-demo/paymentservice:v0.1.0
        ports:
        - containerPort: 50051
        env:
          - name: PORT
            value: "50051"
