apiVersion: apps/v1
kind: Deployment
metadata:
  name: productcatalogservice
  namespace: online-shop-microservices
  labels:
    app: productcatalogservice
spec:
  selector:
    matchLabels:
      app: productcatalogservice
  template:
    metadata:
      labels:
        app: productcatalogservice
    spec:
      containers:
      - name: productcatalogservice
        image: gcr.io/google-samples/microservices-demo/productcatalogservice:v0.1.0
        ports:
        - containerPort: 3550
        env:
          - name: PORT
            value: "3550" 
