apiVersion: apps/v1
kind: Deployment
metadata:
  name: recommedationservice
  namespace: online-shop-microservices
  labels:
    app: recommedationservice
spec:
  selector:
    matchLabels:
      app: recommedationservice
  template:
    metadata:
      labels:
        app: recommedationservice
    spec:
      containers:
      - name: recommedationservice
        image: gcr.io/google-samples/microservices-demo/recommendationservice:v0.2.3
        ports:
        - containerPort: 8080
        env:
          - name: PORT
            value: "8080" 
          - name: DISABLE_TRACKING
            value: "1"
          - name: DISABLE_PROFILER
            value: "1"
          - name: PRODUCT_CATALOG_SERVICE_ADDR
            valueFrom:
              configMapKeyRef:
                name: my-envs-app
                key: PRODUCT_CATALOG_SERVICE_ADDR
        livenessProbe:
          periodSeconds: 5
          exec:
             command: ["/bin/grpc_health_probe","-addr=:8080"]
        readinessProbe:
          periodSeconds: 5
          exec:
             command: ["/bin/grpc_health_probe","-addr=:8080"]
        resources:
          requests:
            cpu: 100m
            memory: 64Mi
          limits:
            cpu: 200m
            memory: 128Mi
