apiVersion: apps/v1
kind: Deployment
metadata:
  name: recommedationservice
  namespace: online-shop-microservices
  labels:
    app: recommedationservice
spec:
  selector:
    matchLabels:
      app: recommedationservice
  template:
    metadata:
      labels:
        app: recommedationservice
    spec:
      containers:
      - name: recommedationservice
        image: gcr.io/google-samples/microservices-demo/recommendationservice:v0.1.0
        ports:
        - containerPort: 8080
        env:
          - name: PORT
            value: "8080" 
          - name: PRODUCT_CATALOG_SERVICE_ADDR
            valueFrom:
              configMapKeyRef:
                name: my-envs-app
                key: PRODUCT_CATALOG_SERVICE_ADDR
       
