apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  namespace: online-shop-microservices
  labels:
    app: redis
spec:
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - name: redis
        image: redis
        ports:
        - containerPort: 6379
        volumeMounts:
          - name: redis-data
            mountPath: /data
        livenessProbe:
          initialDelaySeconds: 5
          periodSeconds: 5
          tcpSocket:
             port: 6379
        readinessProbe:
          initialDelaySeconds: 5
          periodSeconds: 5
          tcpSocket:
             port: 6379
      volumes:
        - name: redis-data
          emptyDir: {}
      
            
